#!bin/sh

# Author : KamakshiKartheek
# Copyright (c) KamakshiKartheek
# Script follows here:

server=`hostname -f`
find /var/log -type f -name '*.log' -mtime +90 -exec rm -f {} \; | mailx -s "Old logs from the server $server" email@domainname.com
